name: build-server

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ----------------------------------------------------------
      # Setup
      # ----------------------------------------------------------

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: "5.x"

      - name: Calculate Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          targetPath: server

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('client/insight/yarn.lock', 'client/backup-viewer/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # ----------------------------------------------------------
      # Test and Build
      # ----------------------------------------------------------

      - name: Server TestSuite
        run: |
          tzutil /s "Pacific Standard Time"
          dotnet test server/test

      - run: yarn --cwd client/insight install --frozen-lockfile
      - run: yarn --cwd client/insight test
      - run: yarn --cwd client/insight run build

      - name: Build MachineFramework
        run: dotnet pack -c Release --include-symbols /p:Version="${{ steps.gitversion.outputs.semVer }}" server/lib/BlackMaple.MachineFramework
      - name: Build Mazak
        run: dotnet pack -c Release --include-symbols /p:Version="${{ steps.gitversion.outputs.semVer }}" server/machines/mazak
      - name: Build Makino
        run: dotnet pack -c Release --include-symbols /p:Version="${{ steps.gitversion.outputs.semVer }}" server/machines/makino
      - name: Build Niigata
        run: dotnet pack -c Release --include-symbols /p:Version="${{ steps.gitversion.outputs.semVer }}" server/machines/niigata

      # ----------------------------------------------------------
      # Publish
      # ----------------------------------------------------------

      - name: Publish MachineFramework
        run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json server\lib\BlackMaple.MachineFramework\bin\Release\*.nupkg
      - name: Publish Mazak
        run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json server\machines\mazak\bin\Release\*.nupkg
      - name: Publish Makino
        run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json server\machines\makino\bin\Release\*.nupkg
      - name: Publish Niigata
        run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json server\machines\niigata\bin\Release\*.nupkg
