name: CI

on:
  push:
    tags-ignore:
      - "v*"
      - "insightapi-*"
    branches-ignore:
      - main
      - release/*

jobs:
  server:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Server TestSuite
        run: |
          tzutil /s "Pacific Standard Time"
          dotnet test server/test --collect:"XPlat Code Coverage"

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          directory: server/test/TestResults
          flags: server-unittests

      - name: API Build
        run: dotnet build client/csharp-api

      - name: Reverse proxy build
        run: dotnet build server/reverse-proxy

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            client/insight/node_modules
            client/backup-viewer/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('client/insight/yarn.lock', 'client/backup-viewer/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install client deps
        run: yarn --cwd client/insight install --frozen-lockfile
      - name: Client Test Suite
        run: yarn --cwd client/insight test
      - name: Client Main Build
        run: yarn --cwd client/insight run build
      - name: Client Demo Build
        run: yarn --cwd client/insight run build-demo

      - name: Install backup-viewer deps
        run: yarn --cwd client/backup-viewer install --frozen-lockfile
      - name: Backup-Viewer Build
        run: yarn --cwd client/backup-viewer run build
