name: release-insight

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      # ----------------------------------------------------------
      # Setup
      # ----------------------------------------------------------

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      # ----------------------------------------------------------
      # Test and Build
      # ----------------------------------------------------------

      - name: Server TestSuite
        run: |
          tzutil /s "Pacific Standard Time"
          dotnet test server/test

      - run: yarn --cwd client/insight install --frozen-lockfile --network-timeout 1000000
      - run: yarn --cwd client/insight test
      - run: yarn --cwd client/insight run build

      - name: Build Mazak
        shell: pwsh
        run: ./build/insight-installer-build.ps1 mazak $ENV:GITHUB_REF.Substring(11)

      - name: Build Makino
        shell: pwsh
        run: ./build/insight-installer-build.ps1 makino $ENV:GITHUB_REF.Substring(11)

      - name: Install Backup Viewer Deps
        run: yarn --cwd client/backup-viewer install --frozen-lockfile

      - name: Update Backup Viewer Version
        shell: pwsh
        run: yarn --cwd client/backup-viewer version --no-git-tag-version --new-version $ENV:GITHUB_REF.Substring(11)

      # ----------------------------------------------------------
      # Release
      # ----------------------------------------------------------

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: FMS Insight ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Mazak
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installers/FMS Insight Mazak Install.msi
          asset_name: FMS Insight Mazak Install.msi
          asset_content_type: application/octet-stream

      - name: Upload Makino
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installers/FMS Insight Makino Install.msi
          asset_name: FMS Insight Makino Install.msi
          asset_content_type: application/octet-stream

      - name: Build and Upload Backup Viewer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn --cwd client/backup-viewer run dist --publish=always
